apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: osc-operator-dev-catalog
  namespace: openshift-marketplace
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  displayName: OSC Operator Dev Catalog
  sourceType: grpc
  image: "{{ .Values.dev.image | default "https://quay.io/repository/redhat-user-workloads/ose-osc-tenant/osc-test-fbc:latest" }}"
  publisher: Confidential Containers Team
