apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trustee-core
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  source:
    repoURL: https://github.com/beraldoleal/helms
    targetRevision: main
    path: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
