apiVersion: v1
kind: ConfigMap
metadata:
  name: osc-feature-gates
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  confidential: "{{ .Values.confidential.enabled | default false }}"
---
{{- if .Values.peerpods.enabled }}
{{- $provider := .Values.peerpods.provider | default "" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: peer-pods-cm
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  CLOUD_PROVIDER: "{{ $provider }}"
  DISABLECVM: "{{ not (.Values.confidential.enabled) }}"
  FOO: "bar"
{{- $config := index .Values.peerpods.providersConfigs "all" | default dict }}
{{- range $key, $value := $config }}
  {{ $key }}: "{{ $value }}"
{{- end }}

{{- $config := index .Values.peerpods.providersConfigs $provider | default dict }}
{{- range $key, $value := $config }}
  {{ $key }}: "{{ $value }}"
{{- end }}
{{- end }}
