apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-policy
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  namespace: {{ .Release.Namespace }}
data:
  policy.rego:
    package policy
    default allow = true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rvps-reference-values
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  namespace: {{ .Release.Namespace }}
data:
  reference-values.json: |
    [
    ]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kbs-config-cm
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  namespace: {{ .Release.Namespace }}
data:
  kbs-config.toml: |
    [http_server]
    sockets = ["0.0.0.0:8080"]
    insecure_http = true

    [admin]
    insecure_api = true
    auth_public_key = "/etc/auth-secret/publicKey"

    [attestation_token]
    insecure_key = true
    attestation_token_type = "CoCo"

    [attestation_service]
    type = "coco_as_builtin"
    work_dir = "/opt/confidential-containers/attestation-service"
    policy_engine = "opa"

      [attestation_service.attestation_token_broker]
      type = "Ear"
      policy_dir = "/opt/confidential-containers/attestation-service/policies"

      [attestation_service.attestation_token_config]
      duration_min = 5

      [attestation_service.rvps_config]
      type = "BuiltIn"

        [attestation_service.rvps_config.storage]
        type = "LocalJson"
        file_path = "/opt/confidential-containers/rvps/reference-values/reference-values.json"

    [[plugins]]
    name = "resource"
    type = "LocalFs"
    dir_path = "/opt/confidential-containers/kbs/repository"

    [policy_engine]
    policy_path = "/opt/confidential-containers/opa/policy.rego"
