apiVersion: v1
kind: Pod
metadata:
  name: kbs-client
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  namespace: {{ .Release.Namespace }}
spec:
  restartPolicy: Never
  containers:
    - name: kbs-client
      image: quay.io/confidential-containers/kbs-client:v0.11.0
      env:
        - name: TRUSTEE_URL
          value: >
            {{- if .Values.crossCluster.enabled }}
            http://foobar
            {{- else }}
            http://kbs-service.{{ .Release.Namespace }}:8080
            {{- end }}
      command:
        - /bin/sh
        - -c
        - |
          echo "Fetching key from $TRUSTEE_URL..."
          kbs-client --url "$TRUSTEE_URL" get-resource --path default/kbsres1/key1 || exit 1
          echo "Success. Sleeping for inspection..."
          sleep 3600
