---
dev:
  # Enable development mode for the operator.
  # This means it will use a custom catalog source and image.
  enabled: true

  # Only used for development purposes, not for production.
  # For production, the official fbc will be used.
  image: quay.io/redhat-user-workloads/ose-osc-tenant/osc-test-fbc:osc-test-fbc-on-push-xq2c2-build-image-index 
