apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-kbsconfig-crd
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  template:
    spec:
      containers:
        - name: wait
          image: quay.io/openshift/origin-cli:4.19
          command:
            - /bin/bash
            - -c
            - |
              for i in {1..60}; do
                oc get crd kbsconfigs.confidentialcontainers.org && exit 0
                sleep 5
              done
              echo "Timed out waiting for CRD"
              exit 1
      restartPolicy: Never
  backoffLimit: 0
