# trustee-og.yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: trustee-operator-group
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  targetNamespaces:
  - trustee-operator-system
