apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trustee-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
rules:
  - apiGroups: ["apiextensions.k8s.io", "route.openshift.io"]
    resources: ["customresourcedefinitions", "routes"]
    verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  kind: ClusterRole
  name: trustee-manager
  apiGroup: rbac.authorization.k8s.io
