{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kbs-service
spec:
  to:
    kind: Service
    name: kbs-service
  port:
    targetPort: kbs-port
  tls:
    termination: {{ .Values.route.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.insecurePolicy }}
{{- end }}
