apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: trustee-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: trustee-operator
  source: {{ if or .Values.isDevBuild (hasKey .Values "image") }}trustee-operator-dev-catalog{{ else }}redhat-operators{{ end }}
  sourceNamespace: openshift-marketplace
