apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: trustee-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: trustee-operator
  source: {{ if .Values.dev.enabled }}trustee-operator-dev-catalog{{ else }}redhat-operators{{ end }}
  sourceNamespace: openshift-marketplace
