{{- if .Values.customCatalog.enabled }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: qe-osc-catalog
  namespace: openshift-marketplace
spec:
  displayName: OSC QE Quay Catalog Source
  image: "quay.io/openshift_sandboxed_containers/openshift-sandboxed-containers-operator-catalog:{{ .Chart.AppVersion }}-{{ .Values.customCatalog.operatorBuild }}"
  publisher: OSC QE
  sourceType: grpc
{{- end }}
