{{- define "catalogSource" -}}
{{- if .Values.customCatalog.enabled }}qe-osc-catalog{{ else }}redhat-operators{{ end }}
{{- end -}}

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sandboxed-containers-operator
  namespace: openshift-sandboxed-containers-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: sandboxed-containers-operator
  sourceNamespace: openshift-marketplace
  source: {{ template "catalogSource" . }}
  startingCSV: sandboxed-containers-operator.v{{ .Chart.AppVersion }}
