---
global:
  hubClusterDomain: hub.example.com
  localCluster: local.example.com

isDevBuild: true

# Only used by dev builds. Default is to use latest image.
image: quay.io/redhat-user-workloads/ose-osc-tenant/trustee-fbc-4-19:on-pr-4b6aec2e163ba59a6cef582a4f103411a30ff98f

route:
  enabled: true

  # TLS termination type:
  # - edge: TLS ends at the router (default)
  # - passthrough: TLS passes through to the pod
  # - reencrypt: TLS between client and router, and router and pod
  termination: edge

  # Insecure traffic handling:
  # - None: reject HTTP
  # - Redirect: redirect HTTP to HTTPS
  # - Allow: serve both HTTP and HTTPS
  insecurePolicy: Allow
